/**
 * documentStore.ts — the Reference Corpus seam.
 *
 * The narrow read-only interface the Integrity Gate checks cross, plus the pure
 * helpers both adapters share (module composition, archive manifest generation).
 *
 * Two adapters implement this interface today:
 *   - scripts/validate.ts  — fs-backed, with an optional Repair capability
 *   - src/data/repository.ts — glob-backed, read-only (web app)
 */

/** One module of the Parent document (reference/NN-slug.md). */
export interface ModuleDoc {
  /** Filename, e.g. "05-configuration-system.md". */
  filename: string;
  /** Leading number, e.g. 5. */
  number: number;
  /** Slug part of the filename, e.g. "configuration-system". */
  slug: string;
  /** H1/H2-derived title. */
  title: string;
  rawContent: string;
}

/** One native JSON Schema (schemas/*.schema.json). */
export interface SchemaDoc {
  filename: string;
  /** Parsed schema object; undefined when the file was invalid JSON. */
  schema?: Record<string, any>;
  /** Set by the CLI adapter when the schema file is not valid JSON. */
  error?: string;
}

/** One evidence probe (EV-###). */
export interface ProbeDoc {
  evId: string;
  number: number;
  title: string;
  status: string;
}

/** One citation from §19 Works Cited. */
export interface CitationDoc {
  number: number;
  title: string;
  url: string;
  category: string;
  slug: string;
  /** Repo-relative snapshot path, e.g. evidence/sources/docs/01-foo.md. */
  snapshotPath: string;
  isDuplicate: boolean;
  duplicateOf?: number | null;
}

/** Result of one Integrity Gate check. */
export type CheckStatus = 'pass' | 'fail' | 'na';

export interface CheckResult {
  id: string;
  name: string;
  category: string;
  status: CheckStatus;
  messages: string[];
  details: string[];
}

/** Optional repair capability — only the CLI adapter implements it. */
export interface RepairStore {
  rebuildParent(): void;
  pruneOrphans(): number;
  syncManifest(): void;
  regenerateEvidence(): void;
}

/**
 * The seam: everything the 12 checks need to know about the repository.
 * Read-only, so the web app can satisfy it from glob-loaded strings.
 */
export interface DocumentStore {
  getModules(): ModuleDoc[];
  getSchemas(): SchemaDoc[];
  getProbes(): ProbeDoc[];
  getCitations(): CitationDoc[];
  /** Repo-relative paths of archived snapshot files (evidence/sources/**). */
  getSnapshotFiles(): string[];
  /** Frontmatter of an archived snapshot, or null if unknown. */
  getSnapshotHeader(snapshotPath: string): Record<string, string> | null;
  /** Raw text of evidence/sources/index.md, or null if absent. */
  getManifestText(): string | null;
  /** Raw text of antigravity-reference.md, or null if absent. */
  getParentComposed(): string | null;
  /** Raw content of any repo file by repo-relative path, or null. */
  getDocument(relPath: string): string | null;
  /** True when a repo-relative path exists on disk / in the loaded corpus. */
  canResolvePath(relPath: string): boolean;
  /**
   * Check-12 capability. The CLI adapter implements it (evidence-index
   * regeneration); the browser omits it and check 12 reports 'na'.
   */
  checkEvidenceIndexSync?: () => { inSync: boolean; message?: string };
  repair?: RepairStore;
}

const SEP = '\n\n---\n\n';
export const GEN_NOTE = '<!-- Generated by scripts/build.ts from reference/ — do not edit by hand. -->\n\n';

/**
 * Pure module composition — the core of scripts/build.ts.
 * Modules must already be in ascending number order.
 */
export function composeModules(modules: { filename: string; content: string }[]): string {
  const parts: string[] = [];
  for (const m of modules) {
    let content = m.content.trimEnd();
    // In reference/*.md modules, relative links to root directories like docs/ or schemas/
    // use ../docs/ or ../schemas/. When composed into antigravity-reference.md at ROOT,
    // adjust leading ../ references so they point cleanly from root.
    content = content.replace(/\]\(\.\.\/(docs\/|schemas\/|evidence\/|scripts\/)/g, ']($1');
    parts.push(content);
  }
  return GEN_NOTE + parts.join(SEP) + '\n';
}

export const MANIFEST_GEN_NOTE = '<!-- Generated by scripts/fetch_sources.ts — do not edit by hand. -->\n';

/**
 * Pure archive-manifest generation — the same table the CLI's
 * evidenceRegistry.generateManifestText() produces.
 */
export function buildManifestText(
  citations: CitationDoc[],
  readHeader: (snapshotPath: string) => Record<string, string> | null
): string {
  const lines = [
    MANIFEST_GEN_NOTE.trimEnd(),
    '',
    '# Source Archive Index',
    '',
    'Status of every citation in section 19 (`reference/19-works-cited.md`), regenerated by `scripts/fetch_sources.ts`.',
    '',
    '| # | Category | Title | File | Status | Fetched |',
    '|---|---|---|---|---|---|',
  ];

  for (const c of citations) {
    const n = c.number;
    if (c.isDuplicate) {
      lines.push(`| ${n} | ${c.category} | ${c.title} | — | duplicate of #${c.duplicateOf} | — |`);
      continue;
    }
    const numPadded = String(n).padStart(2, '0');
    const name = `${numPadded}-${c.slug}.md`;
    const snapPath = c.snapshotPath;
    const header = readHeader(snapPath);
    if (header) {
      const link = `[${name}](${c.category}/${name})`;
      lines.push(`| ${n} | ${c.category} | ${c.title} | ${link} | ${header.status || '?'} | ${header.fetched || '?'} |`);
    } else {
      lines.push(`| ${n} | ${c.category} | ${c.title} | — | missing | — |`);
    }
  }

  return lines.join('\n') + '\n';
}

/** Normalize a repo-relative path for comparison. */
export function normalizePath(p: string): string {
  return p.replace(/^\//, '').replace(/^\.\//, '').replace(/\/+/g, '/').replace(/\/$/, '');
}

/** Resolve a repo-relative link target (e.g. "../docs/x.md") against a base dir. */
export function resolveRepoRelative(baseDir: string, target: string): string {
  const cleanTarget = target.split('#')[0].split('?')[0];
  if (!cleanTarget) return '';
  const segments = (baseDir ? baseDir + '/' : '') + cleanTarget;
  const parts: string[] = [];
  for (const seg of segments.split('/')) {
    if (seg === '' || seg === '.') continue;
    if (seg === '..') {
      parts.pop();
    } else {
      parts.push(seg);
    }
  }
  return parts.join('/');
}

/** One archived snapshot file (evidence/sources/**) as the store sees it. */
export interface SnapshotInput {
  /** Repo-relative (or /-prefixed) path. */
  path: string;
  rawContent: string;
}

/** Frontmatter facts needed to build a flat citation list. */
export interface SnapshotMeta {
  sourceNum: number;
  category: string;
  title: string;
  url: string;
}

/**
 * Build the flat citation list the archive manifest is generated from.
 * Duplicate detection mirrors scripts/lib/evidenceRegistry.ts: first citation
 * for a trailing-slash-normalized URL wins; later ones with a different number
 * are marked as duplicates.
 */
export function flattenCitations(
  inputs: SnapshotInput[],
  metaOf: (rawContent: string) => SnapshotMeta
): CitationDoc[] {
  const items: CitationDoc[] = inputs.map(input => {
    const relPath = normalizePath(input.path);
    const filename = relPath.split('/').pop() || '';
    const m = filename.match(/^(\d+)-(.*)\.md$/);
    const fileNum = m ? parseInt(m[1], 10) : 0;
    const slug = m ? m[2] : filename.replace('.md', '');
    const meta = metaOf(input.rawContent);
    return {
      number: meta.sourceNum || fileNum,
      title: meta.title || slug,
      url: meta.url || '',
      category: meta.category,
      slug,
      snapshotPath: relPath,
      isDuplicate: false,
      duplicateOf: null,
    };
  });

  const urlToFirst: Record<string, number> = {};
  for (const c of items) {
    const normUrl = c.url.replace(/\/+$/, '');
    if (urlToFirst[normUrl] === undefined) {
      urlToFirst[normUrl] = c.number;
    } else if (c.number !== urlToFirst[normUrl]) {
      c.isDuplicate = true;
      c.duplicateOf = urlToFirst[normUrl];
    }
  }
  return items.sort((a, b) => a.number - b.number);
}
