/**
 * evidenceRegistry.ts — Pure Evidence & Citation Domain Module.
 *
 * Single home for Section 19 Works Cited parsing, Empirical Probe cataloging
 * (EV-001..EV-020), URL normalization, snapshot grouping, cross-reference
 * graph construction, and archive manifest generation.
 *
 * Pure and environment-agnostic: zero Node fs imports. Both the CLI fs adapter
 * (scripts/lib/evidenceRegistry.ts) and the web app (src/data/repository.ts)
 * cross this seam.
 */

import {
  parseFrontmatterMap,
  scanCitationBadges,
  scanTextMentions,
  scanFileLinks,
  parseWorksCitedEntry,
} from './markdownCore';
import type { DocumentStore } from './documentStore';
import type { TabType } from '../types';

export const TAG_FOLDER: Record<string, string> = {
  DOCS: 'docs',
  GOOGLE: 'google',
  PROTOCOL: 'protocol',
  COMMUNITY: 'community',
};

export const GEN_NOTE = '<!-- Generated by scripts/fetch_sources.ts — do not edit by hand. -->\n';

/** Clean title string to URL-safe hyphenated slug. */
export function slugifyTitle(title: string): string {
  const s = title.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return s.replace(/^-+|-+$/g, '');
}

/** Compute standard filename slug for a citation URL and title. */
export function slugFor(url: string, title: string): string {
  try {
    const parsed = new URL(url);
    const pathSegments = parsed.pathname.replace(/\/+$/, '').split('/').filter(Boolean);
    let segs = pathSegments;
    if (segs.length > 0 && segs[0] === 'docs') {
      segs = segs.slice(1);
    }
    if (segs.length > 0 && /^\d+$/.test(segs[segs.length - 1])) {
      return slugifyTitle(title);
    }
    if (segs.length === 0) {
      return 'landing';
    }
    return segs.slice(-2).join('-').toLowerCase();
  } catch {
    return slugifyTitle(title);
  }
}

/**
 * Normalizes a URL for canonical matching and duplicate detection.
 * - Strips protocols (http/https)
 * - Lowercases hostname
 * - Removes default ports and trailing slashes
 * - Strips redundant trailing index files (/index.html, /index.md)
 * - Removes standard tracking query parameters (utm_*, ref, source)
 */
export function normalizeCanonicalUrl(rawUrl: string): string {
  if (!rawUrl) return '';
  let url = rawUrl.trim();

  // Strip protocol
  url = url.replace(/^https?:\/\//i, '');

  // Strip www prefix
  url = url.replace(/^www\./i, '');

  // Strip hash anchors
  url = url.split('#')[0];

  // Clean query params (keep query if meaningful, or strip tracking)
  const [base, query] = url.split('?');
  let cleanQuery = '';
  if (query) {
    const params = new URLSearchParams(query);
    ['utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content', 'ref', 'source'].forEach(p =>
      params.delete(p)
    );
    const qs = params.toString();
    if (qs) cleanQuery = `?${qs}`;
  }

  let cleanBase = base.toLowerCase().replace(/\/+$/, '');
  cleanBase = cleanBase.replace(/\/(index\.html|index\.md|index)$/i, '');

  return cleanBase + cleanQuery;
}

/** Parse frontmatter map from raw snapshot content. */
export function parseSnapshotHeader(rawContent: string): Record<string, string> {
  return parseFrontmatterMap(rawContent);
}

/** Detailed frontmatter metadata for an archived source. */
export function parseSourceFrontmatter(rawContent: string): {
  sourceNum: number;
  category: 'docs' | 'google' | 'protocol' | 'community';
  title: string;
  url: string;
  finalUrl: string;
  fetched: string;
  status: number | string;
  license: string;
  checksum?: string;
} {
  const meta = parseFrontmatterMap(rawContent);
  const urlInBody = rawContent.match(/URL:\s*(https?:\/\/[^\s\n\r]+)/i) || rawContent.match(/Source:\s*(https?:\/\/[^\s\n\r]+)/i);

  const numVal = parseInt(meta['source'] || meta['number'] || '0', 10);
  const catVal = (meta['category'] || 'community').toLowerCase() as 'docs' | 'google' | 'protocol' | 'community';
  const urlVal = meta['url'] || (urlInBody ? urlInBody[1] : '');
  const finalUrlVal = meta['final_url'] || urlVal;

  return {
    sourceNum: isNaN(numVal) ? 0 : numVal,
    category: ['docs', 'google', 'protocol', 'community'].includes(catVal) ? catVal : 'community',
    title: meta['title'] || '',
    url: urlVal,
    finalUrl: finalUrlVal,
    fetched: meta['fetched'] || '2026-08-13',
    status: meta['status'] || 200,
    license: meta['license'] || 'CC-BY-4.0',
    checksum: meta['checksum'],
  };
}

export interface Citation {
  number: number;
  title: string;
  url: string;
  category: string; // 'docs', 'google', 'protocol', 'community'
  slug: string;
  snapshotPath: string; // Repo-relative path
  duplicateOf?: number | null;
  isDuplicate: boolean;
}

export interface EvidenceProbe {
  evId: string;
  number: number;
  title: string;
  status: string;
  rawText: string;
}

export interface MergedSourceItem {
  number: number;
  filename: string;
  category: 'docs' | 'google' | 'protocol' | 'community';
  title: string;
  url: string;
  finalUrl?: string;
  rawContent: string;
  fetched?: string;
  status?: number | string;
  license?: string;
}

export interface SourceReferenceLocation {
  targetType: 'reference' | 'evidence' | 'adr' | 'schema' | 'doc';
  targetId: string;
  targetTitle: string;
  sectionTitle?: string;
  lineNumber: number;
  lineText: string;
  contextSnippet: string;
  matchType: 'badge' | 'url' | 'file_link' | 'works_cited' | 'text_mention';
  matchedText: string;
  deepLink: {
    tab: TabType;
    selectedId: string;
    headingId?: string;
  };
}

export interface SourceCitation {
  id: string;
  number: number;
  citationNumbers: number[];
  slug: string;
  title: string;
  category: 'docs' | 'google' | 'protocol' | 'community';
  url: string;
  finalUrl?: string;
  canonicalUrl: string;
  filename: string;
  filenames: string[];
  rawContent: string;
  archivedDate?: string;
  license?: string;
  status?: number | string;
  isDuplicateGroup?: boolean;
  duplicateCount?: number;
  mergedSources?: MergedSourceItem[];
  referenceLocations: SourceReferenceLocation[];
}

export interface SourceArchiveStats {
  totalSnapshots: number;
  uniqueCanonicalRecords: number;
  duplicateGroupsCount: number;
  totalReferenceLocations: number;
  byCategory: {
    docs: number;
    google: number;
    protocol: number;
    community: number;
  };
}

export interface RawSourceInput {
  path: string;
  rawContent: string;
}

/** Parse Section 19 Works Cited markdown into a structured Map of Citations. */
export function parseCitationsFromText(worksCitedText: string): Map<number, Citation> {
  const lines = worksCitedText.split(/\r?\n/);
  const rawItems: { number: number; title: string; url: string; category: string; duplicateOf?: number | null }[] = [];
  let currentCat: string | null = null;

  for (const line of lines) {
    const bareTag = scanCitationBadges(line).find(
      b => b.numbers.length === 0 && TAG_FOLDER[b.tag] !== undefined
    );
    if (bareTag && line.startsWith('#')) {
      currentCat = TAG_FOLDER[bareTag.tag] || null;
      continue;
    }

    const entry = parseWorksCitedEntry(line);
    if (!entry) continue;
    if (entry.tag) {
      rawItems.push({
        number: entry.number,
        title: entry.title,
        url: entry.url,
        category: TAG_FOLDER[entry.tag] || 'community',
      });
    } else if (currentCat) {
      rawItems.push({ number: entry.number, title: entry.title, url: entry.url, category: currentCat });
    }
  }

  rawItems.sort((a, b) => a.number - b.number);

  const urlToFirst: Record<string, number> = {};
  for (const r of rawItems) {
    const normUrl = r.url.replace(/\/+$/, '');
    if (urlToFirst[normUrl] === undefined) {
      urlToFirst[normUrl] = r.number;
    } else {
      if (r.number !== urlToFirst[normUrl]) {
        r.duplicateOf = urlToFirst[normUrl];
      } else {
        r.duplicateOf = null;
      }
    }
  }

  const citations = new Map<number, Citation>();
  for (const r of rawItems) {
    const num = r.number;
    const cat = r.category;
    const dupOf = r.duplicateOf;

    let slug: string;
    let snapPath: string;

    if (dupOf) {
      const primary = citations.get(dupOf)!;
      slug = primary.slug;
      snapPath = primary.snapshotPath;
    } else {
      slug = slugFor(r.url, r.title);
      const numPadded = String(num).padStart(2, '0');
      snapPath = `evidence/sources/${cat}/${numPadded}-${slug}.md`;
    }

    citations.set(num, {
      number: num,
      title: r.title,
      url: r.url,
      category: cat,
      slug,
      snapshotPath: snapPath,
      duplicateOf: dupOf,
      isDuplicate: Boolean(dupOf),
    });
  }

  return citations;
}

/** Parse Evidence Probes from empirical observation markdown text. */
export function parseProbesFromText(evidenceText: string): Map<string, EvidenceProbe> {
  const probes = new Map<string, EvidenceProbe>();
  const sections = evidenceText.split(/(?=##\s+EV-\d+|###\s+EV-\d+)/g);

  for (const sec of sections) {
    const match = sec.match(/(?:##|###)\s+(EV-(\d{3}))[:\s—\-]+([^\n\r]+)/);
    if (match) {
      const evId = match[1].trim();
      const num = parseInt(match[2], 10);
      const title = `${evId}: ${match[3].trim()}`;
      const isResolved = sec.includes('RESOLVED') || sec.includes('Status: RESOLVED') || sec.includes('✅');
      const isVerified = sec.includes('VERIFIED') || sec.includes('CONFIRMED');
      const status = isResolved ? 'CONFIRMED' : isVerified ? 'CONFIRMED' : 'RECORDED';

      probes.set(evId, {
        evId,
        number: num,
        title,
        status,
        rawText: sec.trim(),
      });
    }
  }

  return probes;
}

/**
 * Group raw source snapshot inputs by canonical URL and build unified SourceCitation records.
 */
export function groupDuplicateSources(rawInputs: RawSourceInput[]): SourceCitation[] {
  const parsedItems: MergedSourceItem[] = [];

  for (const item of rawInputs) {
    const filename = item.path.split('/').pop() || '';
    const parts = item.path.split('/');
    const folderCategory = (parts[parts.length - 2] || 'community') as 'docs' | 'google' | 'protocol' | 'community';

    const numMatch = filename.match(/^(\d+)-(.*)\.md$/);
    const fileNum = numMatch ? parseInt(numMatch[1], 10) : 0;
    const slug = numMatch ? numMatch[2] : filename.replace('.md', '');

    const meta = parseSourceFrontmatter(item.rawContent);
    const sourceNumber = meta.sourceNum || fileNum;
    const title = meta.title || slug.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    const category = meta.category || folderCategory;
    const url = meta.url || `https://antigravity.google/ref/${slug}`;
    const finalUrl = meta.finalUrl || url;

    parsedItems.push({
      number: sourceNumber,
      filename,
      category,
      title,
      url,
      finalUrl,
      rawContent: item.rawContent,
      fetched: meta.fetched,
      status: meta.status,
      license: meta.license,
    });
  }

  // Group by normalized canonical URL
  const groupsByCanonicalUrl = new Map<string, MergedSourceItem[]>();

  for (const item of parsedItems) {
    const normUrl = normalizeCanonicalUrl(item.finalUrl || item.url);
    const groupKey = normUrl || `${item.category}:${item.title.toLowerCase().replace(/[^\w]/g, '')}`;

    const group = groupsByCanonicalUrl.get(groupKey) ?? [];
    group.push(item);
    groupsByCanonicalUrl.set(groupKey, group);
  }

  const canonicalCitations: SourceCitation[] = [];

  for (const [canonicalKey, items] of groupsByCanonicalUrl.entries()) {
    items.sort((a, b) => a.number - b.number);
    const primary = items[0];

    const citationNumbers = Array.from(new Set(items.map(i => i.number))).sort((a, b) => a - b);
    const filenames = items.map(i => i.filename);
    const slug = primary.filename.replace(/^(\d+)-/, '').replace(/\.md$/, '');
    const isDuplicateGroup = items.length > 1;

    canonicalCitations.push({
      id: primary.filename,
      number: primary.number,
      citationNumbers,
      slug,
      title: primary.title,
      category: primary.category,
      url: primary.url,
      finalUrl: primary.finalUrl,
      canonicalUrl: canonicalKey,
      filename: primary.filename,
      filenames,
      rawContent: primary.rawContent,
      archivedDate: primary.fetched || '2026-08-13',
      license: primary.license,
      status: primary.status,
      isDuplicateGroup,
      duplicateCount: items.length,
      mergedSources: items,
      referenceLocations: [],
    });
  }

  return canonicalCitations.sort((a, b) => a.number - b.number);
}

/** Pure EvidenceRegistry Domain Engine */
export class EvidenceRegistry {
  private _citations: Map<number, Citation>;
  private _probes: Map<string, EvidenceProbe>;
  private _snapshots: Map<string, { rawContent: string; header: Record<string, string> }>;
  private _canonicalSources: SourceCitation[] | null = null;

  constructor(
    citations: Map<number, Citation>,
    probes: Map<string, EvidenceProbe>,
    snapshots?: Map<string, { rawContent: string; header: Record<string, string> }>
  ) {
    this._citations = citations;
    this._probes = probes;
    this._snapshots = snapshots || new Map();
  }

  static fromTexts(options: {
    worksCitedText: string;
    evidenceText: string;
    snapshots?: RawSourceInput[];
  }): EvidenceRegistry {
    const citations = parseCitationsFromText(options.worksCitedText);
    const probes = parseProbesFromText(options.evidenceText);
    const snapshotsMap = new Map<string, { rawContent: string; header: Record<string, string> }>();

    if (options.snapshots) {
      for (const s of options.snapshots) {
        snapshotsMap.set(s.path, {
          rawContent: s.rawContent,
          header: parseSnapshotHeader(s.rawContent),
        });
      }
    }

    return new EvidenceRegistry(citations, probes, snapshotsMap);
  }

  static fromStore(store: DocumentStore): EvidenceRegistry {
    const worksCitedDoc = store.getDocument('reference/19-works-cited.md') || '';
    const evidenceDoc = store.getDocument('evidence/agy-1.1.12/evidence.md') || '';
    const snapshotPaths = store.getSnapshotFiles();
    const snapshots: RawSourceInput[] = [];

    for (const p of snapshotPaths) {
      const content = store.getDocument(p) || '';
      snapshots.push({ path: p, rawContent: content });
    }

    return EvidenceRegistry.fromTexts({
      worksCitedText: worksCitedDoc,
      evidenceText: evidenceDoc,
      snapshots,
    });
  }

  get citations(): Citation[] {
    return Array.from(this._citations.values()).sort((a, b) => a.number - b.number);
  }

  get probes(): EvidenceProbe[] {
    return Array.from(this._probes.values()).sort((a, b) => a.number - b.number);
  }

  get maxEvidenceNumber(): number {
    const nums = this.probes.map(p => p.number);
    return nums.length > 0 ? Math.max(...nums) : 0;
  }

  get evidenceRange(): string {
    return `EV-001..EV-${String(this.maxEvidenceNumber).padStart(3, '0')}`;
  }

  getCitation(number: number): Citation | undefined {
    return this._citations.get(number);
  }

  getProbe(evId: string): EvidenceProbe | undefined {
    return this._probes.get(evId);
  }

  getSnapshot(pathKey: string): { rawContent: string; header: Record<string, string> } | undefined {
    return this._snapshots.get(pathKey);
  }

  getCanonicalSources(): SourceCitation[] {
    if (!this._canonicalSources) {
      const rawInputs: RawSourceInput[] = Array.from(this._snapshots.entries()).map(([path, data]) => ({
        path,
        rawContent: data.rawContent,
      }));
      this._canonicalSources = groupDuplicateSources(rawInputs);
    }
    return this._canonicalSources;
  }

  /**
   * Generates the markdown content for evidence/sources/index.md.
   */
  generateManifestText(): string {
    const lines = [
      '<!-- Generated by scripts/fetch_sources.ts — do not edit by hand. -->',
      '',
      '# Source Archive Index',
      '',
      'Status of every citation in section 19 (`reference/19-works-cited.md`), regenerated by `scripts/fetch_sources.ts`.',
      '',
      '| # | Category | Title | File | Status | Fetched |',
      '|---|---|---|---|---|---|',
    ];

    for (const c of this.citations) {
      const n = c.number;
      if (c.isDuplicate) {
        lines.push(`| ${n} | ${c.category} | ${c.title} | — | duplicate of #${c.duplicateOf} | — |`);
        continue;
      }
      const numPadded = String(n).padStart(2, '0');
      const name = `${numPadded}-${c.slug}.md`;
      const snapKey = c.snapshotPath;
      const snap = this._snapshots.get(snapKey) || this._snapshots.get(`/${snapKey}`);

      if (snap) {
        const link = `[${name}](${c.category}/${name})`;
        lines.push(`| ${n} | ${c.category} | ${c.title} | ${link} | ${snap.header.status || '?'} | ${snap.header.fetched || '?'} |`);
      } else {
        lines.push(`| ${n} | ${c.category} | ${c.title} | — | missing | — |`);
      }
    }

    return lines.join('\n') + '\n';
  }

  /**
   * Indexes cross-reference locations across modules, probes, and ADRs.
   */
  indexCrossReferences(
    modules: { id: string; number: number; title: string; rawContent: string }[],
    adrRecords: { id: string; number: number; title: string; rawContent: string }[] = []
  ): SourceCitation[] {
    const sources = this.getCanonicalSources();

    const citationMap = new Map<number, SourceCitation>();
    const urlMap = new Map<string, SourceCitation>();
    const fileMap = new Map<string, SourceCitation>();

    for (const c of sources) {
      c.referenceLocations = [];
      for (const num of c.citationNumbers) citationMap.set(num, c);
      if (c.canonicalUrl) urlMap.set(c.canonicalUrl, c);
      const normUrl = normalizeCanonicalUrl(c.url);
      if (normUrl) urlMap.set(normUrl, c);
      if (c.finalUrl) {
        const normFinal = normalizeCanonicalUrl(c.finalUrl);
        if (normFinal) urlMap.set(normFinal, c);
      }
      for (const fn of c.filenames) fileMap.set(fn, c);
    }

    const fileNames = Array.from(fileMap.keys());

    // 1. Reference modules
    for (const mod of modules) {
      const lines = mod.rawContent.split('\n');
      let currentSectionHeading = mod.title;

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const lineNum = i + 1;

        const headingMatch = line.match(/^#{1,4}\s+(.+)$/);
        if (headingMatch) {
          currentSectionHeading = headingMatch[1].replace(/\*\*/g, '').trim();
        }

        // Badges: [DOCS:23]
        for (const badge of scanCitationBadges(line)) {
          for (const num of badge.numbers) {
            const targetCitation = citationMap.get(num);
            if (targetCitation) {
              this._addUniqueLocation(targetCitation.referenceLocations, {
                targetType: 'reference',
                targetId: mod.id,
                targetTitle: `§${mod.number.toString().padStart(2, '0')}. ${mod.title}`,
                sectionTitle: currentSectionHeading,
                lineNumber: lineNum,
                lineText: line.trim(),
                contextSnippet: this._buildContextSnippet(lines, i),
                matchType: 'badge',
                matchedText: badge.matchedText,
                deepLink: { tab: 'reference', selectedId: mod.id },
              });
            }
          }
        }

        // Text mentions: Source #23
        for (const mention of scanTextMentions(line)) {
          const targetCitation = citationMap.get(mention.number);
          if (targetCitation) {
            this._addUniqueLocation(targetCitation.referenceLocations, {
              targetType: 'reference',
              targetId: mod.id,
              targetTitle: `§${mod.number.toString().padStart(2, '0')}. ${mod.title}`,
              sectionTitle: currentSectionHeading,
              lineNumber: lineNum,
              lineText: line.trim(),
              contextSnippet: this._buildContextSnippet(lines, i),
              matchType: 'text_mention',
              matchedText: mention.matchedText,
              deepLink: { tab: 'reference', selectedId: mod.id },
            });
          }
        }

        // File links
        for (const fn of scanFileLinks(line, fileNames)) {
          const targetCitation = fileMap.get(fn);
          if (targetCitation) {
            this._addUniqueLocation(targetCitation.referenceLocations, {
              targetType: 'reference',
              targetId: mod.id,
              targetTitle: `§${mod.number.toString().padStart(2, '0')}. ${mod.title}`,
              sectionTitle: currentSectionHeading,
              lineNumber: lineNum,
              lineText: line.trim(),
              contextSnippet: this._buildContextSnippet(lines, i),
              matchType: 'file_link',
              matchedText: fn,
              deepLink: { tab: 'reference', selectedId: mod.id },
            });
          }
        }

        // Section 19 Works Cited entries
        if (mod.number === 19) {
          const entry = parseWorksCitedEntry(line);
          if (entry) {
            const targetCitation = citationMap.get(entry.number);
            if (targetCitation) {
              this._addUniqueLocation(targetCitation.referenceLocations, {
                targetType: 'reference',
                targetId: mod.id,
                targetTitle: `§19. Works Cited Entry #${entry.number}`,
                sectionTitle: currentSectionHeading,
                lineNumber: lineNum,
                lineText: line.trim(),
                contextSnippet: this._buildContextSnippet(lines, i),
                matchType: 'works_cited',
                matchedText: `Citation #${entry.number}`,
                deepLink: { tab: 'reference', selectedId: mod.id },
              });
            }
          }
        }
      }
    }

    // 2. Probes
    for (const probe of this.probes) {
      const lines = probe.rawText.split('\n');
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const lineNum = i + 1;

        const match = line.match(/(?:Source|source)\s+#?(\d+)/i);
        if (match) {
          const num = parseInt(match[1], 10);
          const targetCitation = citationMap.get(num);
          if (targetCitation) {
            this._addUniqueLocation(targetCitation.referenceLocations, {
              targetType: 'evidence',
              targetId: probe.evId,
              targetTitle: `${probe.evId}: ${probe.title}`,
              sectionTitle: `${probe.evId} Investigation Findings`,
              lineNumber: lineNum,
              lineText: line.trim(),
              contextSnippet: this._buildContextSnippet(lines, i),
              matchType: 'text_mention',
              matchedText: match[0],
              deepLink: { tab: 'evidence', selectedId: probe.evId },
            });
          }
        }
      }
    }

    // 3. ADRs
    for (const adr of adrRecords) {
      const lines = adr.rawContent.split('\n');
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const lineNum = i + 1;

        for (const fn of scanFileLinks(line, fileNames)) {
          const targetCitation = fileMap.get(fn);
          if (targetCitation) {
            this._addUniqueLocation(targetCitation.referenceLocations, {
              targetType: 'adr',
              targetId: adr.id,
              targetTitle: `ADR-${adr.number.toString().padStart(4, '0')}: ${adr.title}`,
              sectionTitle: `ADR Context & Decision`,
              lineNumber: lineNum,
              lineText: line.trim(),
              contextSnippet: this._buildContextSnippet(lines, i),
              matchType: 'file_link',
              matchedText: fn,
              deepLink: { tab: 'adrs', selectedId: adr.id },
            });
          }
        }
      }
    }

    return sources;
  }

  getArchiveStats(rawSnapshotCount?: number): SourceArchiveStats {
    const sources = this.getCanonicalSources();
    const duplicateGroups = sources.filter(c => c.isDuplicateGroup);
    const totalReferences = sources.reduce((sum, c) => sum + c.referenceLocations.length, 0);

    const byCat = { docs: 0, google: 0, protocol: 0, community: 0 };
    for (const c of sources) {
      if (byCat[c.category] !== undefined) {
        byCat[c.category]++;
      }
    }

    return {
      totalSnapshots: rawSnapshotCount !== undefined ? rawSnapshotCount : this._snapshots.size,
      uniqueCanonicalRecords: sources.length,
      duplicateGroupsCount: duplicateGroups.length,
      totalReferenceLocations: totalReferences,
      byCategory: byCat,
    };
  }

  private _buildContextSnippet(lines: string[], targetIndex: number): string {
    const start = Math.max(0, targetIndex - 1);
    const end = Math.min(lines.length, targetIndex + 2);
    return lines.slice(start, end).join('\n');
  }

  private _addUniqueLocation(locations: SourceReferenceLocation[], loc: SourceReferenceLocation) {
    const exists = locations.some(
      l => l.targetId === loc.targetId && l.lineNumber === loc.lineNumber && l.matchType === loc.matchType
    );
    if (!exists) {
      locations.push(loc);
    }
  }
}
