#!/usr/bin/env python3
"""Unified Evidence and Citation Registry.

Deep module encapsulating Section 19 citation resolution, slug generation,
duplicate tracking, archive snapshot path resolution, manifest generation,
and live empirical evidence probe verification.
"""
from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import re
from typing import Dict, List, Optional, Set, Tuple
from urllib.parse import urlparse

try:
    from .doc_inspector import MarkdownDoc
except ImportError:
    from doc_inspector import MarkdownDoc

TAG_FOLDER = {
    "DOCS": "docs",
    "GOOGLE": "google",
    "PROTOCOL": "protocol",
    "COMMUNITY": "community",
}

GEN_NOTE = "<!-- Generated by scripts/fetch_sources.py — do not edit by hand. -->\n"


def slugify_title(title: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", title.lower())
    return s.strip("-")


def slug_for(url: str, title: str) -> str:
    path = urlparse(url).path.rstrip("/")
    segs = [s for s in path.split("/") if s]
    if segs and segs[0] == "docs":
        segs = segs[1:]
    if segs and segs[-1].isdigit():
        return slugify_title(title)
    if not segs:
        return "landing"
    return "-".join(segs[-2:]).lower()


@dataclass(frozen=True)
class Citation:
    """Represents a single numbered citation in the Works Cited module."""
    number: int
    title: str
    url: str
    category: str  # 'docs', 'google', 'protocol', 'community'
    slug: str
    snapshot_path: str
    duplicate_of: Optional[int] = None

    @property
    def is_duplicate(self) -> bool:
        return self.duplicate_of is not None


@dataclass(frozen=True)
class EvidenceProbe:
    """Represents a live empirical probe observation (e.g. EV-001..EV-020)."""
    ev_id: str
    number: int
    title: str
    status: str
    raw_text: str


def read_snapshot_header(path: str) -> Dict[str, str]:
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    m = re.search(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return {}
    kv = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            kv[k.strip()] = v.strip().strip('"')
    return kv


class EvidenceRegistry:
    """Immutable domain registry of all citations and live empirical evidence."""

    def __init__(
        self,
        citations: Dict[int, Citation],
        probes: Dict[str, EvidenceProbe],
        root_dir: str,
    ):
        self._citations = citations
        self._probes = probes
        self.root_dir = root_dir
        self.archive_dir = os.path.join(root_dir, "evidence", "sources")
        self.index_path = os.path.join(self.archive_dir, "index.md")

    @classmethod
    def load(cls, root_dir: Optional[str] = None) -> EvidenceRegistry:
        """Loads and resolves citations and live evidence from the repository."""
        if root_dir is None:
            root_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

        works_cited_path = os.path.join(root_dir, "reference", "19-works-cited.md")
        evidence_path = os.path.join(root_dir, "evidence", "agy-1.1.12", "evidence.md")

        # 1. Parse citations from 19-works-cited.md
        citations = cls._parse_citations(works_cited_path, root_dir)

        # 2. Parse live evidence probes from evidence.md
        probes = cls._parse_probes(evidence_path)

        return cls(citations=citations, probes=probes, root_dir=root_dir)

    @staticmethod
    def _parse_citations(works_cited_path: str, root_dir: str) -> Dict[int, Citation]:
        if not os.path.exists(works_cited_path):
            return {}

        doc = MarkdownDoc.from_file(works_cited_path)
        raw_items: List[Dict] = []
        current_cat: Optional[str] = None

        list_item_re = re.compile(r"^(\d+)\.\s+(.+?)\s+—\s+(https?://\S+)")
        table_row_re = re.compile(r"^\|\s*(\d+)\s*\|\s*`?\[([A-Z0-9-]+)\]`?\s*\|\s*(.+?)\s*\|\s*(https?://\S+)\s*\|")

        for line in doc.lines:
            # Check for category headings: "### Official Docs [DOCS]"
            tag_m = re.search(r"\[(DOCS|GOOGLE|PROTOCOL|COMMUNITY)\]", line)
            if tag_m and line.startswith("#"):
                current_cat = TAG_FOLDER.get(tag_m.group(1))
                continue

            # Check for numbered list items: "1. Hooks — https://..."
            lm = list_item_re.match(line.strip())
            if lm and current_cat:
                num = int(lm.group(1))
                title = lm.group(2).strip()
                url = lm.group(3).strip().rstrip(")")
                raw_items.append({"number": num, "title": title, "url": url, "category": current_cat})
                continue

            # Check for table rows (if structured as table)
            tm = table_row_re.match(line.strip())
            if tm:
                num = int(tm.group(1))
                cat_tag = tm.group(2).strip()
                title = tm.group(3).strip()
                url = tm.group(4).strip()
                cat = TAG_FOLDER.get(cat_tag, "community")
                raw_items.append({"number": num, "title": title, "url": url, "category": cat})

        # Sort raw citations
        raw_items.sort(key=lambda x: x["number"])

        # Detect duplicates by exact URL
        url_to_first: Dict[str, int] = {}
        for r in raw_items:
            norm_url = r["url"].rstrip("/")
            if norm_url not in url_to_first:
                url_to_first[norm_url] = r["number"]
            else:
                if r["number"] != url_to_first[norm_url]:
                    r["duplicate_of"] = url_to_first[norm_url]
                else:
                    r["duplicate_of"] = None

        # Assign slugs and filepaths
        citations: Dict[int, Citation] = {}
        archive_dir = os.path.join(root_dir, "evidence", "sources")

        for r in raw_items:
            num = r["number"]
            cat = r["category"]
            dup_of = r.get("duplicate_of")

            if dup_of:
                # Inherit slug from primary citation
                primary = citations[dup_of]
                slug = primary.slug
                snap_path = primary.snapshot_path
            else:
                slug = slug_for(r["url"], r["title"])
                snap_path = os.path.join(archive_dir, cat, f"{num:02d}-{slug}.md")

            citations[num] = Citation(
                number=num,
                title=r["title"],
                url=r["url"],
                category=cat,
                slug=slug,
                snapshot_path=snap_path,
                duplicate_of=dup_of,
            )

        return citations

    @staticmethod
    def _parse_probes(evidence_path: str) -> Dict[str, EvidenceProbe]:
        if not os.path.exists(evidence_path):
            return {}

        doc = MarkdownDoc.from_file(evidence_path)
        probes: Dict[str, EvidenceProbe] = {}

        # Look for section headers: "### EV-001 - Title" or "### EV-001 Title"
        for sec in doc.sections:
            if not sec.heading:
                continue
            m = re.search(r"\b(EV-(\d{3}))\b", sec.heading.title)
            if m:
                ev_id = m.group(1)
                num = int(m.group(2))
                status = "CONFIRMED" if "CONFIRMED" in sec.content else "RECORDED"
                probes[ev_id] = EvidenceProbe(
                    ev_id=ev_id,
                    number=num,
                    title=sec.heading.title,
                    status=status,
                    raw_text=sec.content,
                )

        return probes

    @property
    def citations(self) -> List[Citation]:
        return sorted(self._citations.values(), key=lambda c: c.number)

    @property
    def probes(self) -> List[EvidenceProbe]:
        return sorted(self._probes.values(), key=lambda p: p.number)

    @property
    def max_evidence_number(self) -> int:
        return max([p.number for p in self.probes]) if self.probes else 0

    @property
    def evidence_range(self) -> str:
        return f"EV-001..EV-{self.max_evidence_number:03d}"

    def get_citation(self, number: int) -> Optional[Citation]:
        return self._citations.get(number)

    def get_probe(self, ev_id: str) -> Optional[EvidenceProbe]:
        return self._probes.get(ev_id)

    def find_missing_snapshots(self) -> List[str]:
        """Finds primary citations that lack an on-disk snapshot file."""
        missing = []
        for c in self.citations:
            if not c.is_duplicate:
                if not os.path.exists(c.snapshot_path):
                    missing.append(c.snapshot_path)
        return missing

    def find_orphan_snapshots(self) -> List[str]:
        """Finds files in evidence/sources/ that do not map to an active citation."""
        valid_paths = {os.path.abspath(c.snapshot_path) for c in self.citations if not c.is_duplicate}
        orphans = []
        for cat in ["docs", "google", "protocol", "community"]:
            cat_dir = os.path.join(self.archive_dir, cat)
            if os.path.exists(cat_dir):
                for fname in os.listdir(cat_dir):
                    if fname.endswith(".md") and fname != "index.md":
                        abs_p = os.path.abspath(os.path.join(cat_dir, fname))
                        if abs_p not in valid_paths:
                            orphans.append(abs_p)
        return orphans

    def generate_manifest_text(self) -> str:
        """Generates the content for evidence/sources/index.md."""
        lines = [
            "<!-- Generated by scripts/fetch_sources.py — do not edit by hand. -->",
            "",
            "# Source Archive Index",
            "",
            "Status of every citation in section 19 (`reference/19-works-cited.md`), regenerated by `scripts/fetch_sources.py`.",
            "",
            "| # | Category | Title | File | Status | Fetched |",
            "|---|---|---|---|---|---|",
        ]

        for c in self.citations:
            n = c.number
            if c.is_duplicate:
                lines.append(
                    f"| {n} | {c.category} | {c.title} | — | duplicate of #{c.duplicate_of} | — |"
                )
                continue
            name = f"{n:02d}-{c.slug}.md"
            path = c.snapshot_path
            if os.path.exists(path):
                h = read_snapshot_header(path)
                link = f"[{name}]({c.category}/{name})"
                lines.append(
                    f"| {n} | {c.category} | {c.title} | {link} | {h.get('status', '?')} | {h.get('fetched', '?')} |"
                )
            else:
                lines.append(
                    f"| {n} | {c.category} | {c.title} | — | missing | — |"
                )

        return "\n".join(lines) + "\n"

    def is_manifest_in_sync(self) -> bool:
        if not os.path.exists(self.index_path):
            return False
        with open(self.index_path, "r", encoding="utf-8") as fh:
            current = fh.read()
        return current.strip() == self.generate_manifest_text().strip()

    def sync_manifest_file(self) -> bool:
        content = self.generate_manifest_text()
        with open(self.index_path, "w", encoding="utf-8") as fh:
            fh.write(content)
        return True


# --- Self-Test Harness ---
if __name__ == "__main__":
    print("Running EvidenceRegistry unit tests...")

    reg = EvidenceRegistry.load()
    assert len(reg.citations) == 46, f"Expected 46 citations, got {len(reg.citations)}"
    assert len(reg.probes) == 20, f"Expected 20 EV probes, got {len(reg.probes)}"
    assert reg.max_evidence_number == 20, f"Expected max EV 20, got {reg.max_evidence_number}"
    assert reg.evidence_range == "EV-001..EV-020"

    missing = reg.find_missing_snapshots()
    assert len(missing) == 0, f"Expected 0 missing snapshots, got {len(missing)}"

    orphans = reg.find_orphan_snapshots()
    assert len(orphans) == 0, f"Expected 0 orphans, got {len(orphans)}"

    assert reg.is_manifest_in_sync(), "Manifest index.md out of sync with registry computation"

    print(f"✓ All EvidenceRegistry tests passed ({len(reg.citations)} citations, {len(reg.probes)} probes, 0 orphans).")
