import * as fs from 'fs';
import * as path from 'path';
import { MarkdownDoc } from './docInspector';
import { parseFrontmatterMap, scanCitationBadges, parseWorksCitedEntry } from '../../src/lib/markdownCore';

export const TAG_FOLDER: Record<string, string> = {
  DOCS: 'docs',
  GOOGLE: 'google',
  PROTOCOL: 'protocol',
  COMMUNITY: 'community',
};

export const GEN_NOTE = '<!-- Generated by scripts/fetch_sources.ts — do not edit by hand. -->\n';

export function slugifyTitle(title: string): string {
  const s = title.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return s.replace(/^-+|-+$/g, '');
}

export function slugFor(url: string, title: string): string {
  try {
    const parsed = new URL(url);
    const pathSegments = parsed.pathname.replace(/\/+$/, '').split('/').filter(Boolean);
    let segs = pathSegments;
    if (segs.length > 0 && segs[0] === 'docs') {
      segs = segs.slice(1);
    }
    if (segs.length > 0 && /^\d+$/.test(segs[segs.length - 1])) {
      return slugifyTitle(title);
    }
    if (segs.length === 0) {
      return 'landing';
    }
    return segs.slice(-2).join('-').toLowerCase();
  } catch {
    return slugifyTitle(title);
  }
}

export interface Citation {
  number: number;
  title: string;
  url: string;
  category: string; // 'docs', 'google', 'protocol', 'community'
  slug: string;
  snapshotPath: string;
  duplicateOf?: number | null;
  isDuplicate: boolean;
}

export interface EvidenceProbe {
  evId: string;
  number: number;
  title: string;
  status: string;
  rawText: string;
}

/** Read the frontmatter of an archived snapshot as a string map (core parser). */
export function readSnapshotHeader(filePath: string): Record<string, string> {
  if (!fs.existsSync(filePath)) {
    return {};
  }
  const text = fs.readFileSync(filePath, 'utf-8');
  return parseFrontmatterMap(text);
}

export class EvidenceRegistry {
  private _citations: Map<number, Citation>;
  private _probes: Map<string, EvidenceProbe>;
  rootDir: string;
  archiveDir: string;
  indexPath: string;

  constructor(citations: Map<number, Citation>, probes: Map<string, EvidenceProbe>, rootDir: string) {
    this._citations = citations;
    this._probes = probes;
    this.rootDir = rootDir;
    this.archiveDir = path.join(rootDir, 'evidence', 'sources');
    this.indexPath = path.join(this.archiveDir, 'index.md');
  }

  static load(rootDir?: string): EvidenceRegistry {
    if (!rootDir) {
      rootDir = process.cwd();
    }

    const worksCitedPath = path.join(rootDir, 'reference', '19-works-cited.md');
    const evidencePath = path.join(rootDir, 'evidence', 'agy-1.1.12', 'evidence.md');

    const citations = EvidenceRegistry._parseCitations(worksCitedPath, rootDir);
    const probes = EvidenceRegistry._parseProbes(evidencePath);

    return new EvidenceRegistry(citations, probes, rootDir);
  }

  private static _parseCitations(worksCitedPath: string, rootDir: string): Map<number, Citation> {
    if (!fs.existsSync(worksCitedPath)) {
      return new Map();
    }

    const doc = MarkdownDoc.fromFile(worksCitedPath);
    const rawItems: { number: number; title: string; url: string; category: string; duplicateOf?: number | null }[] = [];
    let currentCat: string | null = null;

    for (const line of doc.lines) {
      // Section headings carry a bare category tag: "### Official Docs [DOCS]"
      const bareTag = scanCitationBadges(line).find(
        b => b.numbers.length === 0 && TAG_FOLDER[b.tag] !== undefined
      );
      if (bareTag && line.startsWith('#')) {
        currentCat = TAG_FOLDER[bareTag.tag] || null;
        continue;
      }

      const entry = parseWorksCitedEntry(line);
      if (!entry) continue;
      if (entry.tag) {
        // Table rows carry their own category tag.
        rawItems.push({
          number: entry.number,
          title: entry.title,
          url: entry.url,
          category: TAG_FOLDER[entry.tag] || 'community',
        });
      } else if (currentCat) {
        rawItems.push({ number: entry.number, title: entry.title, url: entry.url, category: currentCat });
      }
    }

    rawItems.sort((a, b) => a.number - b.number);

    const urlToFirst: Record<string, number> = {};
    for (const r of rawItems) {
      const normUrl = r.url.replace(/\/+$/, '');
      if (urlToFirst[normUrl] === undefined) {
        urlToFirst[normUrl] = r.number;
      } else {
        if (r.number !== urlToFirst[normUrl]) {
          r.duplicateOf = urlToFirst[normUrl];
        } else {
          r.duplicateOf = null;
        }
      }
    }

    const citations = new Map<number, Citation>();
    const archiveDir = path.join(rootDir, 'evidence', 'sources');

    for (const r of rawItems) {
      const num = r.number;
      const cat = r.category;
      const dupOf = r.duplicateOf;

      let slug: string;
      let snapPath: string;

      if (dupOf) {
        const primary = citations.get(dupOf)!;
        slug = primary.slug;
        snapPath = primary.snapshotPath;
      } else {
        slug = slugFor(r.url, r.title);
        const numPadded = String(num).padStart(2, '0');
        snapPath = path.join(archiveDir, cat, `${numPadded}-${slug}.md`);
      }

      citations.set(num, {
        number: num,
        title: r.title,
        url: r.url,
        category: cat,
        slug,
        snapshotPath: snapPath,
        duplicateOf: dupOf,
        isDuplicate: Boolean(dupOf),
      });
    }

    return citations;
  }

  private static _parseProbes(evidencePath: string): Map<string, EvidenceProbe> {
    if (!fs.existsSync(evidencePath)) {
      return new Map();
    }

    const doc = MarkdownDoc.fromFile(evidencePath);
    const probes = new Map<string, EvidenceProbe>();

    for (const sec of doc.sections) {
      if (!sec.heading) continue;
      const m = sec.heading.title.match(/\b(EV-(\d{3}))\b/);
      if (m) {
        const evId = m[1];
        const num = parseInt(m[2], 10);
        const status = sec.content.includes('CONFIRMED') ? 'CONFIRMED' : 'RECORDED';
        probes.set(evId, {
          evId,
          number: num,
          title: sec.heading.title,
          status,
          rawText: sec.content,
        });
      }
    }

    return probes;
  }

  get citations(): Citation[] {
    return Array.from(this._citations.values()).sort((a, b) => a.number - b.number);
  }

  get probes(): EvidenceProbe[] {
    return Array.from(this._probes.values()).sort((a, b) => a.number - b.number);
  }

  get maxEvidenceNumber(): number {
    const nums = this.probes.map(p => p.number);
    return nums.length > 0 ? Math.max(...nums) : 0;
  }

  get evidenceRange(): string {
    return `EV-001..EV-${String(this.maxEvidenceNumber).padStart(3, '0')}`;
  }

  getCitation(number: number): Citation | undefined {
    return this._citations.get(number);
  }

  getProbe(evId: string): EvidenceProbe | undefined {
    return this._probes.get(evId);
  }

  findMissingSnapshots(): string[] {
    const missing: string[] = [];
    for (const c of this.citations) {
      if (!c.isDuplicate) {
        if (!fs.existsSync(c.snapshotPath)) {
          missing.push(c.snapshotPath);
        }
      }
    }
    return missing;
  }

  findOrphanSnapshots(): string[] {
    const validPaths = new Set(
      this.citations.filter(c => !c.isDuplicate).map(c => path.resolve(c.snapshotPath))
    );
    const orphans: string[] = [];
    for (const cat of ['docs', 'google', 'protocol', 'community']) {
      const catDir = path.join(this.archiveDir, cat);
      if (fs.existsSync(catDir)) {
        const files = fs.readdirSync(catDir);
        for (const fname of files) {
          if (fname.endsWith('.md') && fname !== 'index.md') {
            const absP = path.resolve(path.join(catDir, fname));
            if (!validPaths.has(absP)) {
              orphans.push(absP);
            }
          }
        }
      }
    }
    return orphans;
  }

  generateManifestText(): string {
    const lines = [
      '<!-- Generated by scripts/fetch_sources.ts — do not edit by hand. -->',
      '',
      '# Source Archive Index',
      '',
      'Status of every citation in section 19 (`reference/19-works-cited.md`), regenerated by `scripts/fetch_sources.ts`.',
      '',
      '| # | Category | Title | File | Status | Fetched |',
      '|---|---|---|---|---|---|',
    ];

    for (const c of this.citations) {
      const n = c.number;
      if (c.isDuplicate) {
        lines.push(`| ${n} | ${c.category} | ${c.title} | — | duplicate of #${c.duplicateOf} | — |`);
        continue;
      }
      const numPadded = String(n).padStart(2, '0');
      const name = `${numPadded}-${c.slug}.md`;
      const snapPath = c.snapshotPath;
      if (fs.existsSync(snapPath)) {
        const h = readSnapshotHeader(snapPath);
        const link = `[${name}](${c.category}/${name})`;
        lines.push(`| ${n} | ${c.category} | ${c.title} | ${link} | ${h.status || '?'} | ${h.fetched || '?'} |`);
      } else {
        lines.push(`| ${n} | ${c.category} | ${c.title} | — | missing | — |`);
      }
    }

    return lines.join('\n') + '\n';
  }

  isManifestInSync(): boolean {
    if (!fs.existsSync(this.indexPath)) {
      return false;
    }
    const current = fs.readFileSync(this.indexPath, 'utf-8');
    return current.trim() === this.generateManifestText().trim();
  }

  syncManifestFile(): boolean {
    const content = this.generateManifestText();
    fs.writeFileSync(this.indexPath, content, 'utf-8');
    return true;
  }
}

// Self test harness
if (process.argv[1]?.endsWith('evidenceRegistry.ts')) {
  console.log('Running EvidenceRegistry unit tests [TS]...');
  const reg = EvidenceRegistry.load();
  if (reg.citations.length !== 73) throw new Error(`Expected 73 citations, got ${reg.citations.length}`);
  if (reg.probes.length !== 20) throw new Error(`Expected 20 EV probes, got ${reg.probes.length}`);
  if (reg.maxEvidenceNumber !== 20) throw new Error(`Expected max EV 20, got ${reg.maxEvidenceNumber}`);
  if (reg.evidenceRange !== 'EV-001..EV-020') throw new Error(`Expected EV-001..EV-020, got ${reg.evidenceRange}`);

  const missing = reg.findMissingSnapshots();
  if (missing.length !== 0) throw new Error(`Expected 0 missing snapshots, got ${missing.length}`);

  const orphans = reg.findOrphanSnapshots();
  if (orphans.length !== 0) throw new Error(`Expected 0 orphans, got ${orphans.length}`);

  if (!reg.isManifestInSync()) throw new Error('Manifest index.md out of sync with registry computation');

  console.log(`✓ All EvidenceRegistry tests passed (${reg.citations.length} citations, ${reg.probes.length} probes, 0 orphans) [TS].`);
}
