#!/usr/bin/env python3
"""Compose reference/*.md modules into antigravity-reference.md.

The parent file is a build artifact: edit the modules in reference/ and run
this script. Module files are numbered `NN-slug.md`; composition order is the
sorted filename order, and numbering must be contiguous 0..N.

Usage:
  scripts/build.py            compose once
  scripts/build.py --watch    rebuild whenever a module changes (pure-stdlib polling)
  scripts/build.py --check    exit 0 if the parent is in sync, 1 if stale (no write)
"""
import argparse
import glob
import os
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "reference")
OUT_PATH = os.path.join(ROOT, "antigravity-reference.md")
SEP = "\n\n---\n\n"
GEN_NOTE = "<!-- Generated by scripts/build.py from reference/ — do not edit by hand. -->\n\n"


def module_paths() -> list:
    paths = sorted(glob.glob(os.path.join(SRC_DIR, "[0-9][0-9]-*.md")))
    if not paths:
        sys.exit(f"error: no modules found in {SRC_DIR}/")
    nums = [int(os.path.basename(p)[:2]) for p in paths]
    if nums != list(range(len(nums))):
        sys.exit(f"error: module numbering not contiguous (found {nums}); expected 0..{len(nums) - 1}")
    return paths


def compose() -> str:
    parts = []
    for p in module_paths():
        with open(p, encoding="utf-8") as fh:
            parts.append(fh.read().rstrip("\n"))
    return GEN_NOTE + SEP.join(parts) + "\n"


def write_output(text: str) -> None:
    tmp = OUT_PATH + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(tmp, OUT_PATH)


def do_build() -> str:
    text = compose()
    write_output(text)
    print(f"built {os.path.basename(OUT_PATH)} ({len(text.splitlines())} lines) from {len(module_paths())} modules")
    return text


def snapshot() -> dict:
    return {p: os.stat(p).st_mtime_ns for p in module_paths()}


def watch() -> None:
    last = snapshot()
    do_build()
    print(f"watching {SRC_DIR}/ for changes (Ctrl+C to stop)...")
    try:
        while True:
            time.sleep(1.0)
            cur = snapshot()
            changed = [p for p in cur if cur[p] != last.get(p)]
            if changed:
                print(f"change detected: {os.path.basename(changed[0])}")
                last = cur
                do_build()
    except KeyboardInterrupt:
        print("\nstopped.")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--watch", action="store_true", help="rebuild whenever a module changes")
    ap.add_argument("--check", action="store_true", help="exit 0 if parent is in sync, 1 if stale (no write)")
    args = ap.parse_args()

    if args.check:
        try:
            with open(OUT_PATH, encoding="utf-8") as fh:
                current = fh.read()
        except FileNotFoundError:
            current = ""
        if current == compose():
            print("ok: antigravity-reference.md is in sync with reference/")
            return 0
        print("stale: antigravity-reference.md differs from reference/ (run scripts/build.py)", file=sys.stderr)
        return 1

    if args.watch:
        watch()
        return 0

    do_build()
    return 0


if __name__ == "__main__":
    sys.exit(main())
