#!/usr/bin/env python3
"""Archive cited sources from reference/19-works-cited.md into evidence/sources/.

For each citation in the Works Cited module (section 19), fetch the page and
store a readable Markdown snapshot at:

    evidence/sources/<category>/NN-slug.md

where NN is the citation number from section 19 (the filename is a citation
pointer back to the works-cited list) and <category> mirrors the source tag
(docs | google | protocol | community).

Each file carries a YAML-style header recording provenance: citation number,
title, URL, fetch date, and HTTP status. After every run the script
regenerates evidence/sources/index.md — the archive manifest — so the index
can never drift from the files (same contract as build.py --check).

Dedup rule: when two citations share a URL (e.g. #2 and #62 both point at the
CLI Reference page), the page is archived once under the lowest number and the
higher citation is recorded in the manifest as a duplicate.

Dependencies: python3 stdlib + pandoc (HTML -> Markdown conversion).

Usage:
  fetch_sources.py                       fetch every citation in section 19
  fetch_sources.py --category docs       fetch only [DOCS] citations
  fetch_sources.py --category docs --category google
  fetch_sources.py --force               re-fetch even when the file exists
  fetch_sources.py --check               exit 0 if the archive is in sync, 1 if not
"""
import argparse
import datetime
import gzip
import os
import zlib
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from urllib.parse import urlparse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKS_CITED = os.path.join(ROOT, "reference", "19-works-cited.md")
ARCHIVE_DIR = os.path.join(ROOT, "evidence", "sources")
INDEX_PATH = os.path.join(ARCHIVE_DIR, "index.md")
GEN_NOTE = "<!-- Generated by scripts/fetch_sources.py — do not edit by hand. -->\n"
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0 Safari/537.36"
)
FETCH_TIMEOUT = 30

# Citation-number ranges in the Works Cited module that encode the source tag.
RANGES = {
    "docs": range(1, 30),
    "google": range(30, 37),
    "protocol": range(37, 38),
    "community": range(38, 53),
}
TAG_FOLDER = {
    "DOCS": "docs",
    "GOOGLE": "google",
    "PROTOCOL": "protocol",
    "COMMUNITY": "community",
}

# "1. Hooks — https://antigravity.google/docs/hooks"
# URL capture stops at the first whitespace so trailing notes survive, e.g.
# "35. Configuration — https://.../configuration/ (relocated; ...)".
LIST_ITEM = re.compile(r"^(\d+)\. (.+?) — (https?://\S+?)(?=\s|$)")
# "| 53 | `[DOCS]` | /agents Panel Documentation | https://... |"
TABLE_ROW = re.compile(r"^\| (\d+) \| `?\[([A-Z0-9-]+)\]`? \| (.+?) \| (https?://\S+) \|$")
FRONT = re.compile(r"^---\n(.*?)\n---\n", re.S)


def load_citations() -> dict:
    """Parse every numbered citation in the Works Cited module.

    Returns {number: {"number", "title", "url", "category"}}. The category is
    derived from the citation-number ranges for the list sections and from the
    inline source tag for the "New Sources Identified" table.
    """
    with open(WORKS_CITED, encoding="utf-8") as fh:
        lines = fh.read().splitlines()

    citations = {}
    for raw in lines:
        line = raw.strip()
        m = LIST_ITEM.match(line)
        if m:
            n = int(m.group(1))
            cat = next((folder for folder, rng in RANGES.items() if n in rng), None)
            if cat:
                citations[n] = {
                    "number": n,
                    "title": m.group(2).strip(),
                    "url": m.group(3).strip(),
                    "category": cat,
                }
            continue
        m = TABLE_ROW.match(line)
        if m:
            n = int(m.group(1))
            folder = TAG_FOLDER.get(m.group(2))
            if folder:
                citations[n] = {
                    "number": n,
                    "title": m.group(3).strip(),
                    "url": m.group(4).strip(),
                    "category": folder,
                }
    return citations


def resolve_duplicates(citations: dict) -> None:
    """Mark citations whose URL is already archived under a lower number."""
    by_url = {}
    for n in sorted(citations):
        url = citations[n]["url"]
        if url in by_url:
            citations[n]["duplicate_of"] = by_url[url]
        else:
            by_url[url] = n


def slugify_title(title: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", title.lower())
    return s.strip("-")


def slug_for(rec: dict) -> str:
    """Descriptive tail of the filename, derived from the URL path.

    Falls back to the citation title when the path has no usable segments
    (e.g. the landing page) or ends in a numeric id (e.g. a support article).
    """
    path = urlparse(rec["url"]).path.rstrip("/")
    segs = [s for s in path.split("/") if s]
    if segs and segs[0] == "docs":
        segs = segs[1:]
    if segs and segs[-1].isdigit():
        return slugify_title(rec["title"])
    if not segs:
        return "landing"
    return "-".join(segs[-2:]).lower()


def assign_slugs(citations: dict) -> None:
    used = {}
    for n in sorted(citations):
        rec = citations[n]
        if rec.get("duplicate_of"):
            continue
        base = slug_for(rec)
        slug, i = base, 2
        while slug in used:
            slug, i = f"{base}-{i}", i + 1
        used[slug] = n
        rec["slug"] = slug


def fetch(url: str) -> tuple:
    req = urllib.request.Request(
        url,
        headers={"User-Agent": USER_AGENT, "Accept": "text/html,application/xhtml+xml", "Accept-Encoding": "gzip"},
    )
    with urllib.request.urlopen(req, timeout=FETCH_TIMEOUT) as resp:
        status = resp.status
        final = resp.geturl()
        raw = resp.read()
        charset = resp.headers.get_content_charset() or "utf-8"
        encoding = resp.headers.get("Content-Encoding", "")
    if "gzip" in encoding:
        raw = gzip.decompress(raw)
    elif "deflate" in encoding:
        try:
            raw = zlib.decompress(raw)
        except zlib.error:
            raw = zlib.decompress(raw, -zlib.MAX_WBITS)
    return status, final, raw.decode(charset, errors="replace")


def html_to_markdown(html: str) -> str:
    pandoc = shutil.which("pandoc")
    if not pandoc:
        sys.exit("error: pandoc not found on PATH (required for HTML -> Markdown conversion)")
    p = subprocess.run(
        [pandoc, "-f", "html", "-t", "gfm", "--wrap=none", "-"],
        input=html,
        capture_output=True,
        text=True,
    )
    if p.returncode != 0:
        raise RuntimeError(f"pandoc failed: {p.stderr.strip()[:500]}")
    return p.stdout


def yaml_scalar(s: str) -> str:
    if '"' in s or ":" in s or "{" in s or "}" in s or s.strip() != s:
        return '"' + s.replace('"', '\\"') + '"'
    return s


def write_snapshot(rec: dict, status, final_url: str, fetched: str, body: str) -> str:
    folder = os.path.join(ARCHIVE_DIR, rec["category"])
    os.makedirs(folder, exist_ok=True)
    path = os.path.join(folder, f"{rec['number']:02d}-{rec['slug']}.md")
    header = "\n".join(
        [
            "---",
            f"source: {rec['number']}",
            f"category: {rec['category']}",
            f"title: {yaml_scalar(rec['title'])}",
            f"url: {rec['url']}",
            f"final_url: {final_url}",
            f"fetched: {fetched}",
            f"status: {status}",
            "---",
            "",
        ]
    )
    content = header + body.rstrip() + "\n"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return path


def read_header(path: str) -> dict:
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    m = FRONT.match(text)
    if not m:
        return {}
    kv = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            kv[k.strip()] = v.strip().strip('"')
    return kv


def generate_index(citations: dict) -> str:
    lines = [
        GEN_NOTE,
        "# Source Archive Index",
        "",
        "Status of every citation in section 19 (`reference/19-works-cited.md`), regenerated by `scripts/fetch_sources.py`.",
        "",
        "| # | Category | Title | File | Status | Fetched |",
        "|---|---|---|---|---|---|",
    ]
    for n in sorted(citations):
        rec = citations[n]
        if rec.get("duplicate_of"):
            lines.append(f"| {n} | {rec['category']} | {rec['title']} | — | duplicate of #{rec['duplicate_of']} | — |")
            continue
        name = f"{n:02d}-{rec['slug']}.md"
        path = os.path.join(ARCHIVE_DIR, rec["category"], name)
        if os.path.exists(path):
            h = read_header(path)
            link = f"[{name}]({rec['category']}/{name})"
            lines.append(f"| {n} | {rec['category']} | {rec['title']} | {link} | {h.get('status', '?')} | {h.get('fetched', '?')} |")
        else:
            lines.append(f"| {n} | {rec['category']} | {rec['title']} | — | missing | — |")
    return "\n".join(lines) + "\n"


def snapshot_path(rec: dict) -> str:
    return os.path.join(ARCHIVE_DIR, rec["category"], f"{rec['number']:02d}-{rec['slug']}.md")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument(
        "--category",
        action="append",
        choices=["docs", "google", "protocol", "community"],
        help="source categories to include (repeatable; default: all)",
    )
    ap.add_argument("--force", action="store_true", help="re-fetch pages even when the snapshot exists")
    ap.add_argument("--check", action="store_true", help="exit 0 if the archive is in sync, 1 if not (no writes)")
    args = ap.parse_args()

    citations = load_citations()
    if not citations:
        sys.exit(f"error: no citations parsed from {WORKS_CITED}")
    resolve_duplicates(citations)
    assign_slugs(citations)

    scope = args.category or ["docs", "google", "protocol", "community"]
    selected = {n: c for n, c in citations.items() if c["category"] in scope}
    print(f"scope: {len(selected)} citations ({', '.join(scope)})")

    if args.check:
        missing = [snapshot_path(rec) for n, rec in sorted(selected.items()) if not rec.get("duplicate_of") and not os.path.exists(snapshot_path(rec))]
        index_text = generate_index(selected)
        index_sync = os.path.exists(INDEX_PATH) and open(INDEX_PATH, encoding="utf-8").read() == index_text
        for p in missing:
            print(f"missing: {os.path.relpath(p, ROOT)}", file=sys.stderr)
        if not index_sync:
            print("stale: evidence/sources/index.md differs from the archive (run fetch_sources.py)", file=sys.stderr)
        if not missing and index_sync:
            print(f"ok: {len(selected)} citations in scope are archived and index.md is in sync")
            return 0
        return 1

    fetched_date = datetime.date.today().isoformat()
    ok = fail = skip = 0
    for n, rec in sorted(selected.items()):
        if rec.get("duplicate_of"):
            continue
        path = snapshot_path(rec)
        if os.path.exists(path) and not args.force:
            print(f"skip  #{n:02d} {rec['category']:<9} {os.path.basename(path)} (exists; use --force to re-fetch)")
            skip += 1
            continue
        try:
            status, final, html = fetch(rec["url"])
            body = html_to_markdown(html)
        except urllib.error.HTTPError as e:
            print(f"FAIL  #{n:02d} {rec['category']:<9} {rec['url']} -> HTTP {e.code}")
            fail += 1
            continue
        except Exception as e:
            print(f"FAIL  #{n:02d} {rec['category']:<9} {rec['url']} -> {e}")
            fail += 1
            continue
        write_snapshot(rec, status, final, fetched_date, body)
        print(f"ok    #{n:02d} {rec['category']:<9} {os.path.basename(path)} ({status}, {len(body.splitlines())} lines)")
        ok += 1

    index_text = generate_index(selected)
    with open(INDEX_PATH, "w", encoding="utf-8") as fh:
        fh.write(index_text)
    print(f"wrote {os.path.relpath(INDEX_PATH, ROOT)}")
    print(f"done: {ok} fetched, {skip} skipped, {fail} failed")
    return 0 if fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
