#!/usr/bin/env python3
"""Archive cited sources from reference/19-works-cited.md into evidence/sources/.

For each citation in the Works Cited module (section 19), fetch the page and
store a readable Markdown snapshot at:

    evidence/sources/<category>/NN-slug.md

where NN is the citation number from section 19 (the filename is a citation
pointer back to the works-cited list) and <category> mirrors the source tag
(docs | google | protocol | community).

Each file carries a YAML-style header recording provenance: citation number,
title, URL, fetch date, and HTTP status. After every run the script
regenerates evidence/sources/index.md — the archive manifest — so the index
can never drift from the files (same contract as scripts/build.py --check).

Dedup rule: when two citations share a URL (e.g. #2 and #62 both point at the
CLI Reference page), the page is archived once under the lowest number and the
higher citation is recorded in the manifest as a duplicate.

Dependencies: python3 stdlib + pandoc (HTML -> Markdown conversion).

Usage:
  fetch_sources.py                       fetch every citation in section 19
  fetch_sources.py --category docs       fetch only [DOCS] citations
  fetch_sources.py --category docs --category google
  fetch_sources.py --force               re-fetch even when the file exists
  fetch_sources.py --check               exit 0 if the archive is in sync, 1 if not
  fetch_sources.py --insecure            disable SSL certificate verification (debug only)
"""
import argparse
import datetime
import gzip
import os
import zlib
import re
import shutil
import subprocess
import sys
import ssl
import urllib.error
import urllib.request
from urllib.parse import urlparse

try:
    from bs4 import BeautifulSoup
    HAS_BS4 = True
except ImportError:
    HAS_BS4 = False

try:
    import certifi
    HAS_CERTIFI = True
except ImportError:
    HAS_CERTIFI = False

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKS_CITED = os.path.join(ROOT, "reference", "19-works-cited.md")
ARCHIVE_DIR = os.path.join(ROOT, "evidence", "sources")
INDEX_PATH = os.path.join(ARCHIVE_DIR, "index.md")
GEN_NOTE = "<!-- Generated by scripts/fetch_sources.py — do not edit by hand. -->\n"
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0 Safari/537.36"
)
FETCH_TIMEOUT = 30

TAG_FOLDER = {
    "DOCS": "docs",
    "GOOGLE": "google",
    "PROTOCOL": "protocol",
    "COMMUNITY": "community",
}

# "1. Hooks — https://antigravity.google/docs/hooks"
# URL capture stops at the first whitespace so trailing notes survive, e.g.
# "35. Configuration — https://.../configuration/ (relocated; ...)".
LIST_ITEM = re.compile(r"^(\d+)\. (.+?) — (https?://\S+?)(?=\s|$)")
# "| 53 | `[DOCS]` | /agents Panel Documentation | https://... |"
TABLE_ROW = re.compile(r"^\| (\d+) \| `?\[([A-Z0-9-]+)\]`? \| (.+?) \| (https?://\S+) \|$")
FRONT = re.compile(r"^---\n(.*?)\n---\n", re.S)


from lib.evidence_registry import EvidenceRegistry, Citation, TAG_FOLDER, GEN_NOTE, read_snapshot_header


def make_ssl_context(insecure: bool = False) -> ssl.SSLContext:
    """Return an SSL context for HTTPS fetching."""
    if insecure:
        return ssl._create_unverified_context()
    if HAS_CERTIFI:
        return ssl.create_default_context(cafile=certifi.where())
    return ssl.create_default_context()


def load_citations() -> dict:
    """Parse every numbered citation in the Works Cited module via EvidenceRegistry."""
    reg = EvidenceRegistry.load(ROOT)
    out = {}
    for c in reg.citations:
        out[c.number] = {
            "number": c.number,
            "title": c.title,
            "url": c.url,
            "category": c.category,
            "slug": c.slug,
            "duplicate_of": c.duplicate_of,
        }
    return out


def get_existing_snapshots() -> list:
    """Return paths of all existing snapshot markdown files in category folders."""
    reg = EvidenceRegistry.load(ROOT)
    existing = []
    for cat in TAG_FOLDER.values():
        cat_dir = os.path.join(reg.archive_dir, cat)
        if os.path.isdir(cat_dir):
            for name in sorted(os.listdir(cat_dir)):
                if name.endswith(".md") and name != "index.md":
                    existing.append(os.path.join(cat_dir, name))
    return existing


def find_orphans(citations: Optional[dict] = None) -> list:
    """Find snapshot files on disk that are not referenced in citations."""
    reg = EvidenceRegistry.load(ROOT)
    return reg.find_orphan_snapshots()


def resolve_duplicates(citations: dict) -> None:
    """No-op for backward-compatibility; duplicates are resolved in EvidenceRegistry."""
    pass


def assign_slugs(citations: dict) -> None:
    """No-op for backward-compatibility; slugs are assigned in EvidenceRegistry."""
    pass


def generate_index(citations: Optional[dict] = None) -> str:
    """Generate the complete archive manifest via EvidenceRegistry."""
    reg = EvidenceRegistry.load(ROOT)
    return reg.generate_manifest_text()


def snapshot_path(rec: dict) -> str:
    """Return expected snapshot file path for a citation."""
    return os.path.join(ARCHIVE_DIR, rec["category"], f"{rec['number']:02d}-{rec['slug']}.md")


SOFT_404_URL_PATTERNS = [
    "trk=article_not_found",
    "/404",
    "page_not_found",
    "article_not_found",
    "/error/404",
]
SOFT_404_TEXT_PATTERNS = [
    "we can’t find the page",
    "we cannot find the page",
    "page you’re looking for may have been moved",
    "404 not found",
    "404: this page could not be found",
]


def fetch(url: str, ssl_context: ssl.SSLContext) -> tuple:
    """Fetch URL and return (status, final_url, decoded_html)."""
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": USER_AGENT,
            "Accept": "text/html,application/xhtml+xml",
            "Accept-Encoding": "gzip, deflate",
        },
    )
    with urllib.request.urlopen(req, timeout=FETCH_TIMEOUT, context=ssl_context) as resp:
        status = resp.status
        final = resp.geturl()
        raw = resp.read()
        charset = resp.headers.get_content_charset() or "utf-8"
        encoding = resp.headers.get("Content-Encoding", "").lower()

    if "gzip" in encoding:
        raw = gzip.decompress(raw)
    elif "deflate" in encoding:
        try:
            raw = zlib.decompress(raw)
        except zlib.error:
            raw = zlib.decompress(raw, -zlib.MAX_WBITS)
    decoded = raw.decode(charset, errors="replace")

    # Soft-404 detection
    final_lower = final.lower()
    text_lower = decoded.lower()
    if any(pattern in final_lower for pattern in SOFT_404_URL_PATTERNS) or any(
        pattern in text_lower for pattern in SOFT_404_TEXT_PATTERNS
    ):
        raise urllib.error.HTTPError(final, 404, "Soft 404 (Page Not Found)", resp.headers, None)

    return status, final, decoded


def extract_main_content(html: str) -> str:
    """Isolate primary content from full HTML and strip presentational markup.

    Supports docs platforms (Astro, Mintlify, Docusaurus, GitBook, Dev.to, Reddit).
    """
    soup = BeautifulSoup(html, "html.parser")

    # Decompose site chrome, navigation, sidebars, scripts, styles, SVGs, data-URIs, and anchors
    for selector in [
        "header", "nav", "footer", "script", "style", "noscript", "svg",
        "img[src^='data:']", "a.deep-link-anchor", ".header", ".docs-nav",
        ".page-nav-overlay", ".mobile-menu", ".dropdown-overlay", ".dropdown",
        ".logo-container", ".logo-context-menu", ".header-actions",
        ".header-actions-right", ".docs-section-nav", ".docs-page-nav",
        "#table-of-contents", "#table-of-contents-layout", ".toc", "aside",
        ".breadcrumbs", ".share-buttons"
    ]:
        for tag in soup.select(selector):
            tag.decompose()

    # Prioritized content container selectors for various documentation / blog platforms
    node = None
    for selector in [
        "#content-area", "#content", "div.markdown-content", ".main-content",
        "main", "article", "div[role='main']", ".theme-doc-markdown",
        ".markdown-body", "#article-body", ".article-body", "[data-test-id='post-content']"
    ]:
        node = soup.select_one(selector)
        if node is not None:
            break

    if node is None:
        node = soup.body or soup

    # Strip ALL attributes except href on <a> links and src/alt on <img> tags
    for tag in node.find_all(True):
        allowed = {}
        if tag.name == "a" and "href" in tag.attrs:
            allowed["href"] = tag.attrs["href"]
        elif tag.name == "img":
            if "src" in tag.attrs:
                allowed["src"] = tag.attrs["src"]
            if "alt" in tag.attrs:
                allowed["alt"] = tag.attrs["alt"]
        tag.attrs = allowed

    # Unwrap presentational structural containers (div, span, section, etc.)
    for tag in list(node.find_all(["div", "span", "section", "aside", "header", "footer"])):
        tag.unwrap()

    # Remove empty elements (except standalone void elements like img, hr, br)
    for tag in list(node.find_all(True)):
        if (
            tag.name not in ["img", "hr", "br"]
            and not tag.get_text(strip=True)
            and not tag.find_all(["img", "hr", "br"])
        ):
            tag.decompose()

    return node.decode_contents() if hasattr(node, "decode_contents") else str(node)


def html_to_markdown(html: str) -> str:
    """Convert fetched HTML to GitHub Flavored Markdown using pandoc.

    Only the main content area is converted; site chrome is discarded.
    """
    if not HAS_BS4:
        sys.exit("error: beautifulsoup4 is required. Run: pip install beautifulsoup4")
    pandoc = shutil.which("pandoc")
    if not pandoc:
        sys.exit("error: pandoc not found on PATH (required for HTML -> Markdown conversion)")

    content_html = extract_main_content(html)

    p = subprocess.run(
        [pandoc, "-f", "html", "-t", "gfm", "--wrap=none", "-"],
        input=content_html,
        capture_output=True,
        text=True,
    )
    if p.returncode != 0:
        raise RuntimeError(f"pandoc failed: {p.stderr.strip()[:500]}")
    return p.stdout


def yaml_scalar(s: str) -> str:
    """Quote a string if it contains characters that would break YAML."""
    if '"' in s or ":" in s or "{" in s or "}" in s or s.strip() != s:
        return '"' + s.replace('"', '\\"') + '"'
    return s


def write_snapshot(rec: dict, status, final_url: str, fetched: str, body: str) -> str:
    """Write snapshot file and return its path."""
    folder = os.path.join(ARCHIVE_DIR, rec["category"])
    os.makedirs(folder, exist_ok=True)
    path = os.path.join(folder, f"{rec['number']:02d}-{rec['slug']}.md")
    header = "\n".join(
        [
            "---",
            f"source: {rec['number']}",
            f"category: {yaml_scalar(rec['category'])}",
            f"title: {yaml_scalar(rec['title'])}",
            f"url: {yaml_scalar(rec['url'])}",
            f"final_url: {yaml_scalar(final_url)}",
            f"fetched: {yaml_scalar(fetched)}",
            f"status: {status}",
            "---",
            "",
        ]
    )
    content = header + body.rstrip() + "\n"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return path


def read_header(path: str) -> dict:
    """Read YAML-style header from snapshot and return as dict."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    m = FRONT.match(text)
    if not m:
        return {}
    kv = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            kv[k.strip()] = v.strip().strip('"')
    return kv


def generate_index(citations: dict) -> str:
    """Generate the complete archive manifest.

    Always operates on the full citation set, regardless of `--category`,
    to ensure the index never drifts from the full archive.
    """
    lines = [
        GEN_NOTE,
        "# Source Archive Index",
        "",
        "Status of every citation in section 19 (`reference/19-works-cited.md`), regenerated by `scripts/fetch_sources.py`.",
        "",
        "| # | Category | Title | File | Status | Fetched |",
        "|---|---|---|---|---|---|",
    ]
    for n in sorted(citations):
        rec = citations[n]
        if rec.get("duplicate_of"):
            lines.append(
                f"| {n} | {rec['category']} | {rec['title']} | — | duplicate of #{rec['duplicate_of']} | — |"
            )
            continue
        name = f"{n:02d}-{rec['slug']}.md"
        path = os.path.join(ARCHIVE_DIR, rec["category"], name)
        if os.path.exists(path):
            h = read_header(path)
            link = f"[{name}]({rec['category']}/{name})"
            lines.append(
                f"| {n} | {rec['category']} | {rec['title']} | {link} | {h.get('status', '?')} | {h.get('fetched', '?')} |"
            )
        else:
            lines.append(
                f"| {n} | {rec['category']} | {rec['title']} | — | missing | — |"
            )
    return "\n".join(lines) + "\n"


def snapshot_path(rec: dict) -> str:
    """Return expected snapshot file path for a citation."""
    return os.path.join(ARCHIVE_DIR, rec["category"], f"{rec['number']:02d}-{rec['slug']}.md")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument(
        "--category",
        action="append",
        choices=["docs", "google", "protocol", "community"],
        help="source categories to include (repeatable; default: all)",
    )
    ap.add_argument("--force", action="store_true", help="re-fetch pages even when the snapshot exists")
    ap.add_argument("--check", action="store_true", help="exit 0 if the archive is in sync, 1 if not (no writes)")
    ap.add_argument("--prune", action="store_true", help="delete archived files no longer referenced in section 19")
    ap.add_argument("--insecure", action="store_true", help="disable SSL certificate verification (not recommended)")
    args = ap.parse_args()

    ssl_context = make_ssl_context(args.insecure)

    citations = load_citations()
    if not citations:
        sys.exit(f"error: no citations parsed from {WORKS_CITED}")
    resolve_duplicates(citations)
    assign_slugs(citations)

    # Handle pruning orphaned files
    if args.prune:
        orphans = find_orphans(citations)
        if not orphans:
            print("ok: no orphaned snapshot files found")
        else:
            for p in orphans:
                os.remove(p)
                print(f"pruned: {os.path.relpath(p, ROOT)}")
        if not args.check and not args.force and not args.category:
            index_text = generate_index(citations)
            with open(INDEX_PATH, "w", encoding="utf-8") as fh:
                fh.write(index_text)
            print(f"wrote {os.path.relpath(INDEX_PATH, ROOT)}")
            return 0

    # In --check mode, always validate the full archive, ignoring category filters.
    if args.check:
        missing = [
            snapshot_path(rec)
            for n, rec in sorted(citations.items())
            if not rec.get("duplicate_of") and not os.path.exists(snapshot_path(rec))
        ]
        orphans = find_orphans(citations)
        index_text = generate_index(citations)
        index_sync = os.path.exists(INDEX_PATH) and open(INDEX_PATH, encoding="utf-8").read() == index_text
        for p in missing:
            print(f"missing: {os.path.relpath(p, ROOT)}", file=sys.stderr)
        for p in orphans:
            print(f"orphan:  {os.path.relpath(p, ROOT)}", file=sys.stderr)
        if not index_sync:
            print("stale: evidence/sources/index.md differs from the archive (run fetch_sources.py)", file=sys.stderr)
        if not missing and not orphans and index_sync:
            print(f"ok: all {len(citations)} citations are archived and index.md is in sync")
            return 0
        return 1

    # Normal fetch mode: apply category filter only to which pages we fetch.
    scope = args.category or ["docs", "google", "protocol", "community"]
    selected = {n: c for n, c in citations.items() if c["category"] in scope}
    print(f"scope: {len(selected)} citations ({', '.join(scope)})")

    fetched_date = datetime.date.today().isoformat()
    ok = fail = skip = 0
    for n, rec in sorted(selected.items()):
        if rec.get("duplicate_of"):
            continue
        path = snapshot_path(rec)
        if os.path.exists(path) and not args.force:
            print(f"skip  #{n:02d} {rec['category']:<9} {os.path.basename(path)} (exists; use --force to re-fetch)")
            skip += 1
            continue
        try:
            status, final, html = fetch(rec["url"], ssl_context)
            body = html_to_markdown(html)
        except urllib.error.HTTPError as e:
            print(f"FAIL  #{n:02d} {rec['category']:<9} {rec['url']} -> HTTP {e.code}")
            fail += 1
            continue
        except Exception as e:
            print(f"FAIL  #{n:02d} {rec['category']:<9} {rec['url']} -> {e}")
            fail += 1
            continue
        write_snapshot(rec, status, final, fetched_date, body)
        print(f"ok    #{n:02d} {rec['category']:<9} {os.path.basename(path)} ({status}, {len(body.splitlines())} lines)")
        ok += 1

    # Always regenerate the full index.
    index_text = generate_index(citations)
    with open(INDEX_PATH, "w", encoding="utf-8") as fh:
        fh.write(index_text)
    print(f"wrote {os.path.relpath(INDEX_PATH, ROOT)}")
    print(f"done: {ok} fetched, {skip} skipped, {fail} failed")
    return 0 if fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())