#!/usr/bin/env python3
"""One-time migration: split antigravity-reference.md into reference/ modules.

Splits on top-level `## N.` headings (preamble -> 00-preamble.md, sections
1..20 -> 01-..-20-*.md). Subsection headings like `## 18.1` do NOT match the
top-level pattern and stay inside their parent section module.

After writing the modules, this script composes them in memory (same logic as
build.py) and verifies the composition reproduces the original file exactly
(modulo the generated-note comment that build.py prepends). Running it again
once reference/ exists is a guarded no-op.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC = os.path.join(ROOT, "antigravity-reference.md")
SRC = os.path.join(ROOT, "reference")

# TOC section number -> module slug (kebab-case of the section title)
SLUGS = {
    1: "executive-summary",
    2: "methodology-and-source-classification",
    3: "product-ecosystem-and-identity",
    4: "extensibility-architecture",
    5: "configuration-system",
    6: "permissions-engine",
    7: "cli-command-reference",
    8: "built-in-agent-tool-api",
    9: "sandbox",
    10: "headless-mode",
    11: "browser-integration",
    12: "artifacts-and-implementation-plans",
    13: "enterprise-features",
    14: "workspace-governance-recommendations",
    15: "complete-path-inventory",
    16: "information-sourced-outside-official-docs",
    17: "undocumented-behavioral-contracts",
    18: "remaining-hard-gaps",
    19: "works-cited",
    20: "schema-toolkit-and-native-schemas",
}

HEADING = re.compile(r"^## (\d+)\. ", re.M)
GEN_NOTE = "<!-- Generated by build.py from reference/ — do not edit by hand. -->\n\n"
SEP = "\n\n---\n\n"


def normalize(s: str) -> str:
    """Drop the generated note and standalone section separators so that content
    streams can be compared regardless of separator normalization."""
    s = s.replace(GEN_NOTE, "")
    s = re.sub(r"\n\n---\n\n", "\n\n", s)
    return s.rstrip("\n")  # original lacked a trailing newline; build emits one


def section_content(start: int, end: int, lines: list) -> str:
    """Content of the module starting at 0-based line `start`.

    `end` is the 0-based line of the NEXT top-level heading (or len(lines) for
    the last module). The canonical separator block before the next heading is
    [blank, '---', blank]; when present it is excluded from the module.
    """
    if end < len(lines) and lines[end - 2] == "---":
        return "\n".join(lines[start : end - 3]).rstrip("\n")
    return "\n".join(lines[start:end]).rstrip("\n")


def main() -> int:
    if not os.path.exists(DOC):
        print(f"error: {DOC} not found", file=sys.stderr)
        return 1
    if os.path.isdir(SRC) and os.listdir(SRC):
        print(f"refusing to split: {SRC}/ already exists (delete it first if you really want to re-split)", file=sys.stderr)
        return 1

    with open(DOC, encoding="utf-8") as fh:
        text = fh.read()
    lines = text.split("\n")

    matches = [(m.start(), int(m.group(1))) for m in HEADING.finditer(text)]
    if [n for _, n in matches] != list(range(1, 21)):
        print(f"error: unexpected top-level headings: {[n for _, n in matches]}", file=sys.stderr)
        return 1
    line_of = [text.count("\n", 0, pos) for pos, _ in matches]

    modules = {0: section_content(0, line_of[0], lines)}  # preamble
    for i, sec_no in enumerate([n for _, n in matches], start=1):
        start = line_of[i - 1]
        end = line_of[i] if i < len(line_of) else len(lines)
        modules[sec_no] = section_content(start, end, lines)

    os.makedirs(SRC, exist_ok=True)
    files = {0: os.path.join(SRC, "00-preamble.md")}
    for sec_no in range(1, 21):
        files[sec_no] = os.path.join(SRC, f"{sec_no:02d}-{SLUGS[sec_no]}.md")

    for sec_no, path in files.items():
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(modules[sec_no] + "\n")
        print(f"wrote {os.path.relpath(path, ROOT)} ({len(modules[sec_no].splitlines())} lines)")

    # Round-trip check: compose in memory and compare with the original.
    composed = GEN_NOTE + SEP.join(modules[n] for n in range(0, 21)) + "\n"
    if normalize(composed) == normalize(text):
        print("round-trip: content preserved. Intended diffs only:")
        print("  - generated-note comment prepended by build.py")
        print("  - section separators normalized (original omitted '---' before '## 19. Works Cited')")
        return 0

    import difflib

    diff = list(difflib.unified_diff(text.splitlines(), composed.splitlines(), lineterm=""))
    print(f"round-trip MISMATCH: {len(diff)} diff lines — inspect reference/ before running build.py", file=sys.stderr)
    for line in diff[:40]:
        print(line, file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
